wandb_version: 1

algorithm:
  desc: null
  value: Sequential-ISNE
processing_strategy:
  desc: null
  value: doc_first_depth
chunk_size:
  desc: null
  value: 512
chunk_overlap:
  desc: null
  value: 50
embedding_dim:
  desc: null
  value: 384
dataset:
  desc: null
  value: academic_repositories
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750115358.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 49
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
