wandb_version: 1

embedding_dim:
  desc: null
  value: 384
hidden_dim:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 32
data_normalization:
  desc: null
  value: enabled
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750116611.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      2:
      - 1
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
