_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 32
data_normalization:
    value: enabled
embedding_dim:
    value: 384
epochs:
    value: 50
hidden_dim:
    value: 256
learning_rate:
    value: 0.001
